### ISSUE TITLE
Swap out Redo for Redix

### ISSUE THREAD

**Issue by jeregrine** [phoenixframework/phoenix_pubsub_redis#13]
https://github.com/whatyouhide/redix 

Redix has a very similar API to Redo and is written natively in elixir. Also has the benefits of using fishcakez's excellent Connection abstraction. 

I am planning on taking this on in the coming weeks but if anyone wants to jump on it sooner let me know.

**Comment by chrismccord** [comment]
:+1:

**Comment by mitchellhenke** [comment]
I may steal it this week :grimacing:

**Comment by jeregrine** [comment]
@mitchellhenke just let me know when/if you get started and I'll assign it to you

**Comment by mitchellhenke** [comment]
started a little bit here: https://github.com/phoenixframework/phoenix_pubsub_redis/compare/master...mitchellhenke:redix

at the very least, tests are passing :stuck_out_tongue:

**Comment by mitchellhenke** [comment]
will hopefully finish up this week
