### ISSUE TITLE
I'm new to elixir and get lost to use this in phoenix controller, can show some example at doc

### ISSUE THREAD

**Issue by maple-leaf** [phoenixframework/phoenix_pubsub_redis#33]
I try to understand `pub sub` and `genserver` etc by searching around, But I still get lost and don't know how to get started with this.

I thinks give some basic example on how to use this and when to use this will be good for newbie like me. I get some clues about using this as single model module but not very clear while I completely lose on how to use this inside controller. How I set value to redis? How to get value from redis in order to use it as variable to render page?

**Comment by josevalim** [comment]
Hi @maple-leaf! This is not a redis driver. This is just a backend for pubsub, you would never call it directly. See the redix project if you want to use Redis: https://github.com/whatyouhide/redix

For general help, check out elixirforum.com.
