### ISSUE TITLE
Redis config does not accept the SSL option

### ISSUE THREAD

**Issue by dpick** [phoenixframework/phoenix_pubsub_redis#37]
Redix has an `ssl: true` option so it can connect to a Redis via an encrypted connection. It looks like the Phoenix.PubSub.Redis adapter ignores that option right now :( via this take - https://github.com/phoenixframework/phoenix_pubsub_redis/blob/master/lib/phoenix_pubsub_redis/redis.ex#L58.

If I get some time this week I'll try to send a PR, but for now I'm just opening an issue so people are aware.

**Comment by mitchellhenke** [comment]
@dpick thanks for opening this!

If you don't find the time, I should be able to get to it by the end of the week.

**Comment by dpick** [comment]
Awesome, thanks for the very quick response @mitchellhenke!

**Comment by mitchellhenke** [comment]
I opened #38 if you want to give it a shot.  It seems to work as expected from my testing, and I'll likely come back and merge/release by the end of the week barring any issues.

**Comment by dpick** [comment]
It looks good to me, thanks!

**Comment by mitchellhenke** [comment]
This has been released in `2.1.6`
