### ISSUE TITLE
Update readme and docs with phoenix_pubsub 2 configuration

### ISSUE THREAD

**Issue by tompave** [phoenixframework/phoenix_pubsub_redis#47]
When version 3 [was released](https://github.com/phoenixframework/phoenix_pubsub_redis/commit/eb4e55ae393c97ade0b3b37f667e33f5784e5bdd), it added support for Phoenix.PubSub v2.0, but the configuration instructions in the readme and docs were not updated.

They still show code to configure the pubsub server within Phoenix's endpoint config, which shouldn't be correct for Phoenix 1.5.

**Comment by mitchellhenke** [comment]
Thank you, will get that updated!
