### ISSUE TITLE
Publish a new release?

### ISSUE THREAD

**Issue by dgvncsz0f** [phoenixframework/phoenix_pubsub_redis#56]
Would it be possible to publish a new release of the current master on hex.pm?

**Comment by stoyle** [comment]
Yes please, would be great! Redix is currently our only outdated dep, and cant be updated because of phoenix_pubsub_redis.

**Comment by cliftonmcintosh** [comment]
Same here. I'd love to be able to use this, but I have another dependency already that requires redix >= 0.11.0.

**Comment by chrismccord** [comment]
Done!

**Comment by cliftonmcintosh** [comment]
Thank you!

**Comment by cliftonmcintosh** [comment]
Any chance that could be `{:redix, "~> 0.10 or ~> 1.0"}` instead of `{:redix, "~> 0.10.0 or ~> 1.0"}`? Is redix 0.11 specifically disallowed?
